<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="Enrollment.Properties.Settings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Courses" Member="Courses">
    <Type Name="Course">
      <Column Name="CourseID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="CourseCredit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CreditHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Course1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Course2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Course3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>